using FijiPayroll.Domain.Entities.Common;
using FijiPayroll.Domain.Enumerations;
using System;
using System.Collections.Generic;

namespace FijiPayroll.Domain.Entities.Company;

/// <summary>
/// Domain aggregate representing a company fiscal calendar year.
/// Prevents regeneration of period dates when the calendar is locked.
/// </summary>
public sealed class FiscalCalendar : SoftDeleteEntity
{
    private readonly List<FiscalPeriod> _periods = new();

    private FiscalCalendar() { }

    /// <summary>Gets the company tenant ID.</summary>
    public int CompanyId { get; private set; }

    /// <summary>Gets the fiscal year number (e.g. 2026).</summary>
    public int FiscalYear { get; private set; }

    /// <summary>Gets the start date of the fiscal year.</summary>
    public DateTime StartDate { get; private set; }

    /// <summary>Gets the end date of the fiscal year.</summary>
    public DateTime EndDate { get; private set; }

    /// <summary>Gets a value indicating whether this fiscal calendar is closed.</summary>
    public bool IsClosed { get; private set; }

    /// <summary>Gets the period division structure type of this calendar.</summary>
    public CalendarType CalendarType { get; private set; } = CalendarType.Monthly;

    /// <summary>Gets the username of the administrator who generated this calendar.</summary>
    public string GeneratedBy { get; private set; } = string.Empty;

    /// <summary>Gets the UTC timestamp when this calendar was generated.</summary>
    public DateTime GeneratedUtc { get; private set; }

    /// <summary>Gets a value indicating whether this calendar is locked against regeneration.</summary>
    public bool IsLocked { get; private set; }

    /// <summary>Gets the collection of monthly or custom fiscal periods under this calendar.</summary>
    public IReadOnlyCollection<FiscalPeriod> Periods => _periods.AsReadOnly();

    /// <summary>Factory method to create a new FiscalCalendar.</summary>
    public static FiscalCalendar Create(
        int companyId,
        int fiscalYear,
        DateTime startDate,
        DateTime endDate,
        CalendarType calendarType,
        string generatedBy)
    {
        if (companyId <= 0)
            throw new ArgumentException("Company ID must be positive.", nameof(companyId));
        if (fiscalYear < 2000 || fiscalYear > 2100)
            throw new ArgumentException("Fiscal year must be between 2000 and 2100.", nameof(fiscalYear));
        if (startDate >= endDate)
            throw new ArgumentException("Start date must be before end date.", nameof(startDate));
        if (string.IsNullOrWhiteSpace(generatedBy))
            throw new ArgumentException("Generated by username is required.", nameof(generatedBy));

        return new FiscalCalendar
        {
            CompanyId = companyId,
            FiscalYear = fiscalYear,
            StartDate = startDate,
            EndDate = endDate,
            IsClosed = false,
            CalendarType = calendarType,
            GeneratedBy = generatedBy,
            GeneratedUtc = DateTime.UtcNow,
            IsLocked = false
        };
    }

    /// <summary>Adds a fiscal period breakdown to this calendar.</summary>
    public void AddPeriod(FiscalPeriod period)
    {
        if (IsLocked)
            throw new InvalidOperationException("CALENDAR_LOCKED_ERROR: Cannot add periods to a locked fiscal calendar.");
        if (period == null) throw new ArgumentNullException(nameof(period));

        _periods.Add(period);
    }

    /// <summary>Locks the fiscal calendar to prevent future period generation/updates.</summary>
    public void LockCalendar()
    {
        IsLocked = true;
    }

    /// <summary>Closes the fiscal calendar year.</summary>
    public void CloseCalendar()
    {
        IsClosed = true;
        LockCalendar();
    }
}
