using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using FijiPayroll.Domain.Entities.Payroll;

namespace FijiPayroll.Infrastructure.Services.ComplianceEvidence;

/// <summary>
/// Simple PDF Generator with zero external dependencies. Produces standard PDF binary output.
/// </summary>
public sealed class SimplePdfGenerator
{
    /// <summary>
    /// Generates a binary PDF document containing the core evidence pack summaries.
    /// </summary>
    public byte[] GeneratePdf(Domain.Entities.Payroll.EvidencePack pack)
    {
        if (pack == null) throw new ArgumentNullException(nameof(pack));

        var writer = new SimplePdfWriter();

        // 1. Catalog Object (ID 1)
        writer.AddObject("<< /Type /Catalog /Pages 2 0 R >>");

        // 2. Pages Object (ID 2)
        writer.AddObject("<< /Type /Pages /Kids [3 0 R] /Count 1 >>");

        // 3. Page Object (ID 3)
        writer.AddObject("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.275 841.889] /Resources << /Font << /F1 4 0 R /F2 6 0 R >> >> /Contents 5 0 R >>");

        // 4. Font 1 (ID 4) - Helvetica Regular
        writer.AddObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");

        // 5. Page Content Stream Object (ID 5)
        byte[] contentBytes = BuildContentStream(pack);
        writer.AddObject(contentBytes);

        // 6. Font 2 (ID 6) - Helvetica Bold
        writer.AddObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");

        return writer.Build();
    }

    private static byte[] BuildContentStream(Domain.Entities.Payroll.EvidencePack pack)
    {
        var sb = new StringBuilder();

        // Start text block
        sb.Append("BT\n");

        // Document Title
        sb.Append("/F2 16 Tf\n"); // Bold font size 16
        sb.Append("70 780 Td\n"); // Y = 780
        sb.Append("(FIJI ENTERPRISE PAYROLL - COMPLIANCE EVIDENCE PACK) Tj\n");

        // Subtitle
        sb.Append("/F1 10 Tf\n"); // Regular font size 10
        sb.Append("0 -20 Td\n");  // Move down by 20 units (Y = 760)
        sb.Append($"({EscapePdfText($"Correlation ID: {pack.CorrelationId}  |  Generated: {pack.GeneratedUtc:yyyy-MM-dd HH:mm:ss} UTC")}) Tj\n");
        
        sb.Append("0 -15 Td\n");  // Y = 745
        sb.Append($"({EscapePdfText($"Generated By: {pack.GeneratedBy}")}) Tj\n");

        // Executive Summary Section
        sb.Append("/F2 12 Tf\n"); // Bold font size 12
        sb.Append("0 -30 Td\n");  // Move down 30 (Y = 715)
        sb.Append("(1. EXECUTIVE SUMMARY) Tj\n");

        var summary = pack.ExecutiveSummary;
        sb.Append("/F1 10 Tf\n");
        sb.Append("0 -18 Td\n");  // Y = 697
        sb.Append($"({EscapePdfText($"Company ID: {summary.CompanyId}")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 682
        sb.Append($"({EscapePdfText($"Payroll Run ID: {summary.PayrollRunId}  |  Period: {summary.Period}")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 667
        sb.Append($"({EscapePdfText($"Total Gross Pay: {summary.TotalGross:C}  |  Total PAYE Tax: {summary.TotalPAYE:C}")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 652
        sb.Append($"({EscapePdfText($"Total FNPF Contribution: {summary.TotalFNPF:C}  |  Total Net Pay: {summary.TotalNetPay:C}")}) Tj\n");

        // Ledger Integrity Manifest Section
        sb.Append("/F2 12 Tf\n");
        sb.Append("0 -30 Td\n");  // Y = 622
        sb.Append("(2. LEDGER INTEGRITY MANIFEST) Tj\n");

        var integrity = pack.LedgerIntegrity;
        sb.Append("/F1 10 Tf\n");
        sb.Append("0 -18 Td\n");  // Y = 604
        sb.Append($"({EscapePdfText($"Ledger Record Count: {integrity.RecordCount}")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 589
        sb.Append($"({EscapePdfText($"Verification Timestamp: {integrity.VerificationTimestamp:yyyy-MM-dd HH:mm:ss} UTC")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 574
        sb.Append($"({EscapePdfText($"Integrity Status: {integrity.IntegrityStatus}")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 559
        sb.Append($"({EscapePdfText($"Ledger SHA-256 Hash: {integrity.PayrollLedgerHash}")}) Tj\n");

        // Reconciliation Summary Section
        sb.Append("/F2 12 Tf\n");
        sb.Append("0 -30 Td\n");  // Y = 529
        sb.Append("(3. RECONCILIATION SUMMARY) Tj\n");

        var recon = pack.Reconciliation;
        sb.Append("/F1 10 Tf\n");
        sb.Append("0 -18 Td\n");  // Y = 511
        sb.Append($"({EscapePdfText($"Reconciliation Status: {recon.Status}")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 496
        sb.Append($"({EscapePdfText($"Ledger Gross: {recon.LedgerGross:C}  |  Compliance Gross: {recon.SubmissionGross:C}  |  Variance: {recon.GrossVariance:C}")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 481
        sb.Append($"({EscapePdfText($"Ledger PAYE: {recon.LedgerPaye:C}  |  Compliance PAYE: {recon.SubmissionPaye:C}  |  Variance: {recon.PayeVariance:C}")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 466
        sb.Append($"({EscapePdfText($"Ledger FNPF: {recon.LedgerFnpf:C}  |  Compliance FNPF: {recon.SubmissionFnpf:C}  |  Variance: {recon.FnpfVariance:C}")}) Tj\n");

        // Compliance Validation Summary Section
        sb.Append("/F2 12 Tf\n");
        sb.Append("0 -30 Td\n");  // Y = 436
        sb.Append("(4. COMPLIANCE AUDIT VALIDATION STATUS) Tj\n");

        sb.Append("/F1 10 Tf\n");
        sb.Append("0 -18 Td\n");  // Y = 418
        sb.Append($"({EscapePdfText($"FRCS Validation Count: {pack.ValidationOutput.FrcsValidationResults.Count} issues found")}) Tj\n");
        sb.Append("0 -15 Td\n");  // Y = 403
        sb.Append($"({EscapePdfText($"FNPF Validation Count: {pack.ValidationOutput.FnpfValidationResults.Count} issues found")}) Tj\n");

        // End text block
        sb.Append("ET\n");

        // Draw basic layout border lines using PDF vector graphics operators
        sb.Append("1 w\n"); // Line width 1
        sb.Append("0 G\n"); // Color black (stroke)
        sb.Append("60 790 m 530 790 l S\n"); // Top border line
        sb.Append("60 735 m 530 735 l S\n"); // Subheader line
        sb.Append("60 50 m 530 50 l S\n");   // Bottom footer line

        // Bottom footer page number
        sb.Append("BT /F1 8 Tf 270 35 Td (Page 1 of 1) Tj ET\n");

        string contentString = sb.ToString();
        byte[] contentBytes = Encoding.ASCII.GetBytes(contentString);

        // Wrap stream dictionary header around the content bytes
        string streamHeader = $"<< /Length {contentBytes.Length} >>\nstream\n";
        string streamFooter = "\nendstream\n";

        byte[] headerBytes = Encoding.ASCII.GetBytes(streamHeader);
        byte[] footerBytes = Encoding.ASCII.GetBytes(streamFooter);

        byte[] result = new byte[headerBytes.Length + contentBytes.Length + footerBytes.Length];
        Buffer.BlockCopy(headerBytes, 0, result, 0, headerBytes.Length);
        Buffer.BlockCopy(contentBytes, 0, result, headerBytes.Length, contentBytes.Length);
        Buffer.BlockCopy(footerBytes, 0, result, headerBytes.Length + contentBytes.Length, footerBytes.Length);

        return result;
    }

    private static string EscapePdfText(string text)
    {
        if (string.IsNullOrEmpty(text)) return string.Empty;
        var sb = new StringBuilder();
        foreach (char c in text)
        {
            if (c == '(' || c == ')' || c == '\\')
            {
                sb.Append('\\').Append(c);
            }
            else
            {
                sb.Append(c);
            }
        }
        return sb.ToString();
    }

    private sealed class SimplePdfWriter
    {
        private readonly List<byte[]> _objects = [];
        private readonly List<long> _offsets = [];

        public void AddObject(string content)
        {
            byte[] bytes = Encoding.ASCII.GetBytes(content + "\n");
            AddObject(bytes);
        }

        public void AddObject(byte[] bytes)
        {
            _objects.Add(bytes);
        }

        public byte[] Build()
        {
            using var ms = new MemoryStream();
            
            // 1. PDF Header
            byte[] header = Encoding.ASCII.GetBytes("%PDF-1.4\n");
            ms.Write(header, 0, header.Length);

            // 2. Objects
            for (int i = 0; i < _objects.Count; i++)
            {
                _offsets.Add(ms.Position);

                byte[] objHeader = Encoding.ASCII.GetBytes($"{(i + 1)} 0 obj\n");
                ms.Write(objHeader, 0, objHeader.Length);

                byte[] objBody = _objects[i];
                ms.Write(objBody, 0, objBody.Length);

                byte[] objFooter = Encoding.ASCII.GetBytes("endobj\n");
                ms.Write(objFooter, 0, objFooter.Length);
            }

            long xrefOffset = ms.Position;

            // 3. Cross-reference Table
            StringBuilder xrefBuilder = new StringBuilder();
            xrefBuilder.Append("xref\n");
            xrefBuilder.Append($"0 {(_objects.Count + 1)}\n");
            xrefBuilder.Append("0000000000 65535 f \n");
            for (int i = 0; i < _objects.Count; i++)
            {
                xrefBuilder.Append(string.Format(CultureInfo.InvariantCulture, "{0:D10} 00000 n \n", _offsets[i]));
            }

            // 4. Trailer
            xrefBuilder.Append("trailer\n");
            xrefBuilder.Append($"<< /Size {(_objects.Count + 1)} /Root 1 0 R >>\n");
            xrefBuilder.Append("startxref\n");
            xrefBuilder.Append($"{xrefOffset}\n");
            xrefBuilder.Append("%%EOF\n");

            byte[] trailerBytes = Encoding.ASCII.GetBytes(xrefBuilder.ToString());
            ms.Write(trailerBytes, 0, trailerBytes.Length);

            return ms.ToArray();
        }
    }
}
